.travis.yml, README.md, backend/config.js, backend/model/user.js, backend/package-lock.json, backend/package.json, backend/route/user.js, backend/server.js, backend/tests/main.test.js
Set up backend test template with login and signup tests and backend CI
Related issue: #6
=> Backend test template

backend/swagger.json
Completed API Documentation for the following routes: 
```
[ { path: '/delivery', methods: [ 'GET' ] },
{ path: '/delivery/issue', methods: [ 'POST', 'PUT' ] },
{ path: '/campus', methods: [ 'GET' ] },
{ path: '/campus/issue', methods: [ 'POST', 'DELETE', 'PUT' ] },
{ path: '/user', methods: [ 'GET' ] },
{ path: '/user/login', methods: [ 'GET' ] },
{ path: '/user/signup', methods: [ 'POST' ] } ]
```
Addresses Issue #25 
Locally verified output of API Docs on localhost:5000/api-docs
=> Sprint 1 Backend API Documentation (#25)

README.md, backend/package.json, backend/server.js, frontend/package-lock.json
Set up backend deployment and frontend deployment on Heroku.
https://github.com/20001LastOrder/McGrill_App/issues/12
#30
=> Deploy backend

backend/model/restaurant.js, backend/route/restaurant.js, backend/server.js, backend/tests/main.test.js
=> Restaurant registration

backend/model/menuitem.js, backend/model/restaurant.js
=> add menuitem

backend/model/restaurant.js, backend/route/restaurant.js
=> Fix restaurant api

backend/model/menuitem.js, backend/model/restaurant.js, backend/route/menuitem.js, backend/route/restaurant.js, backend/server.js, backend/tests/main.test.js
Menu items embedded within restaurants. (Restaurant stores an Array of MenuItem ObjectIDs)
Create Menu Item and Edit Menu item works. 
GET Restaurant should also return the id of the restaurant. 
Please link to the issue here: #55 #56 
PostMan query works.
JEST Test written which passes.
=> Menu Items in Restaurant

backend/route/user.js
We need a get user by email API for the frontend to get details of the user on the Edit User Profile page. 
**API**
`/getUser?email=<the-email-goes-here>`
The API takes in an email as a query, and the authorisation token, and returns the specified user (with the password as null)
Tested using Postman.
=> Add a Get User By Email API 

frontend/package-lock.json, frontend/package.json, frontend/src/App.js, frontend/src/components/itemcard.js, frontend/src/components/menu_page.js
Create restaurant's menu page (customer view). Since other frontend flow is not yet implemented, the menu page can be accessed directly by route "/menu". Also, "return all menu items" backend API is not yet ready, the current items showing on the page are mocked data.
=> Create restaurant's menu page (customer view)

backend/package-lock.json, backend/package.json, backend/route/menuitem.js, backend/route/restaurant.js, backend/tests/menu_item_test.js
Implement query all menu items and delete one menu item
#57 #60 
Tested with HTTP tools (postman)
Will implement test later
=> Implement query all menu items and delete one menu item API

frontend/tests/featureDefinitions/Create_New_Restaurant_Owner.js, frontend/tests/featureDefinitions/Create_New_System_Administrator.js, frontend/tests/featureDefinitions/Remove_Manu_Item.js, frontend/tests/featureDefinitions/Remove_User.js, frontend/tests/featureDefinitions/ViewMenuItem.js, frontend/tests/featureDefinitions/ViewRestaurantInfo.js, frontend/tests/featureDefinitions/ViewUserProfile.js, frontend/tests/features/Create_New_Restaurant_Owner.feature, frontend/tests/features/Create_New_System_Administrator.feature, frontend/tests/features/Remove_Manu_Item.feature, frontend/tests/features/Remove_User.feature, frontend/tests/features/ViewMenuItem.feature, frontend/tests/features/ViewUserProfile.feature, package-lock.json
=> add test cases

backend/route/menuitem.js, backend/route/restaurant.js, backend/tests/menu_item_test.js
=> Query MenuItem by name of restaurant 

backend/model/menuitem.js, backend/route/restaurant.js
=> added types to menuItems and query by their types

frontend/tests/features/ID011_Upddate_Order_Status, frontend/tests/features/ID012_View_All_Orders_In_Queue, frontend/tests/features/ID030_View_Cart, frontend/tests/features/ID046_Creat_And_Submit_Order
=> add gerkins files for iteration 2

backend/model/order.js, backend/model/restaurant.js, backend/model/user.js, backend/route/order.js, backend/route/restaurant.js, backend/server.js
Created an Order Model. 
Create Order Post API
View Current Restaurant Orders
View Past Restaurant Orders
Integration Tests through Postman.
=> Order Model, Create Order, View Resto Orders

backend/model/restaurant.js, backend/route/restaurant.js, backend/tests/main.test.js, backend/tests/rest_category_test.js
#100 #99 #98 #118 #119 
And an extra API that adds a list of categories to one of the rest owned by authorized user. 
please read rest_category_test.js
=> Yuxma Category of restaurant

backend/route/restaurant.js, backend/route/user.js, backend/tests/rest_category_test.js, backend/tests/user_test.js
Update user and rest info, ("override" of "restaurant category", so be careful). 
#61 #62 with test
=> Yuxma user rest update

backend/model/restaurant.js, backend/route/admin.js, backend/route/restaurant.js, backend/route/user.js, backend/server.js, backend/swagger.json, backend/tests/main.test.js, backend/tests/rest_category_test.js, backend/tests/restaurant_query_test.js
Added get restaurants by category api and test
https://github.com/20001LastOrder/McGrill_App/issues/119
https://github.com/20001LastOrder/McGrill_App/issues/118
Postman manually tested
Ran ```npm test```
=> Get restaurants by category api

.travis.yml, backend/.env, backend/config.js
Make CI run locally in the container on TravisCI. This should both fix #125 and #124
=> config mongodb for travis ci

backend/route/order.js, backend/route/restaurant.js, backend/server.js, backend/tests/main.test.js, backend/tests/order_test.js
Implemented the order status update API
#111 
Implement with [unit test](https://github.com/20001LastOrder/McGrill_App/blob/pengnanf/backend/tests/order_test.js)
Successful with local test
=> implement order status update api

backend/tests/query_all_restaurant_test.js
=> query all restaurants test passed

backend/swagger.json
=> updated api documentation for querying all restaurants
